### ISSUE TITLE
Rename readme.md

### ISSUE THREAD

**Issue by henriquecrang** [renatolew/PersonalPage#1]
It is a good practice to use capital letters in the name of the readme file. It this case, it would be README.md .

It is important because many applications used to navigate trough folders, like ls for example, order things with all the upper case ascii codes being shown before the lower case ones. So, since you want your user to read this document before doing anything else, using the upper case is a way to help him noticing the file.

**Comment by renatolew** [comment]
Thank you for the feedback! The issue was fixed!
